[53 hotfix] GCS IO safety and test bucket size calls [BW-411]
broadinstitute/cromwell pull request #5997
Opened 2020-10-29 21:18 UTC by cjllanwarne

2020-10-29 21:45 UTC, mcovarr approved these changes

2020-10-29 22:35 UTC, mcovarr requested changes
CromwellTimeoutSpec does not appear to exist on 53 hotfix

2020-10-30 13:42 UTC, grsterin approved these changes

2020-10-30 16:32 UTC, cjllanwarne commented
Merging for expediency despite two flaky test failures because (1) the 53_hotfix branch will be retested and added to before being deployed, and (2) the hotfix is not being used in situations relevant to the test failures. The tests which failed were:
* CWL conformance on PAPIv2 beta
* PAPIv2 beta on MariaDB

2020-10-30 16:34 UTC, mcovarr approved these changes

2020-10-30 16:37 UTC, merged