Add deleter metrics modeled on archiver metrics [BW-632]
broadinstitute/cromwell pull request #6340
Opened 2021-05-07 16:49 UTC by rsasch

Closes https://broadworkbench.atlassian.net/browse/BW-632

2021-05-07 19:57 UTC, aednichols commented on services/src/main/scala/cromwell/services/metadata/impl/deleter/DeleteMetadataActor.scala
> +  private val deleterMetricsBasePath: NonEmptyList[String] = MetadataServiceActor.MetadataInstrumentationPrefix :+ "archiver"
Copy-paste error?
```suggestion
  private val deleterMetricsBasePath: NonEmptyList[String] = MetadataServiceActor.MetadataInstrumentationPrefix :+ "deleter"
```

2021-05-07 21:10 UTC, rsasch commented on services/src/main/scala/cromwell/services/metadata/impl/deleter/DeleteMetadataActor.scala
> +  private val deleterMetricsBasePath: NonEmptyList[String] = MetadataServiceActor.MetadataInstrumentationPrefix :+ "archiver"
whoops — thanks for the catch!

2021-05-07 21:44 UTC, salonishah11 commented on database/sql/src/main/scala/cromwell/database/slick/tables/WorkflowMetadataSummaryEntryComponent.scala
> +      if summaryEntry.workflowStatus.inSet(workflowStatuses)
I think when looking for workflows to delete, we might not need to check the workflow status. We only need to check for archive status and end time just like [workflowIdsByArchiveStatusAndEndedOnOrBeforeThresholdTimestamp](https://github.com/broadinstitute/cromwell/blob/187c49defd1ef3c2df4133e6e9b9c92edfce79b4/database/sql/src/main/scala/cromwell/database/slick/tables/WorkflowMetadataSummaryEntryComponent.scala#L74-L81)

2021-05-10 15:09 UTC, aednichols approved these changes

2021-05-10 21:02 UTC, salonishah11 requested changes
1 change requested and few minor copy paste errors

2021-05-10 21:51 UTC, salonishah11 approved these changes
Just 1 small nit comment [here](https://github.com/broadinstitute/cromwell/pull/6340/files#r629661412). Otherwise LGTM 👍

2021-05-11 16:25 UTC, merged