Update FiveMinuteIntro: Java 11 requirement
broadinstitute/cromwell pull request #6830
Opened 2022-08-16 14:04 UTC by sjfleming

I have 
```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
```
and I was getting 
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/hsqldb/jdbcDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.zaxxer.hikari.HikariConfig.attemptFromContextLoader(HikariConfig.java:970)
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:480)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.$anonfun$forConfig$3(HikariCPJdbcDataSource.scala:33)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.$anonfun$forConfig$3$adapted(HikariCPJdbcDataSource.scala:33)
	at scala.Option.foreach(Option.scala:437)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:33)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:21)
	at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:47)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig(JdbcBackend.scala:341)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig$(JdbcBackend.scala:337)
	at slick.jdbc.JdbcBackend$$anon$1.forConfig(JdbcBackend.scala:32)
	at slick.jdbc.JdbcBackend.createDatabase(JdbcBackend.scala:35)
	at slick.jdbc.JdbcBackend.createDatabase$(JdbcBackend.scala:35)
	at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:574)
	at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:574)
	at slick.basic.DatabaseConfig$$anon$1.db$lzycompute(DatabaseConfig.scala:103)
	at slick.basic.DatabaseConfig$$anon$1.db(DatabaseConfig.scala:102)
	at cromwell.database.slick.SlickDatabase.<init>(SlickDatabase.scala:73)
	at cromwell.database.slick.EngineSlickDatabase.<init>(EngineSlickDatabase.scala:15)
	at cromwell.database.slick.EngineSlickDatabase$.fromParentConfig(EngineSlickDatabase.scala:10)
	at cromwell.services.EngineServicesStore$.engineDatabaseInterface$lzycompute(EngineServicesStore.scala:13)
	at cromwell.services.EngineServicesStore$.engineDatabaseInterface(EngineServicesStore.scala:12)
	at cromwell.server.CromwellSystem.$init$(CromwellSystem.scala:27)
	at cromwell.CromwellEntryPoint$$anon$1.<init>(CromwellEntryPoint.scala:122)
	at cromwell.CromwellEntryPoint$.$anonfun$buildCromwellSystem$1(CromwellEntryPoint.scala:122)
	at scala.util.Try$.apply(Try.scala:210)
	at cromwell.CromwellEntryPoint$.buildCromwellSystem(CromwellEntryPoint.scala:122)
	at cromwell.CromwellEntryPoint$.runSingle(CromwellEntryPoint.scala:65)
	at cromwell.CromwellApp$.runCromwell(CromwellApp.scala:14)
	at cromwell.CromwellApp$.delayedEndpoint$cromwell$CromwellApp$1(CromwellApp.scala:25)
	at cromwell.CromwellApp$delayedInit$body.apply(CromwellApp.scala:3)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at cromwell.CromwellApp$.main(CromwellApp.scala:3)
	at cromwell.CromwellApp.main(CromwellApp.scala)
```
when trying to run Cromwell 83.  I see that the Java requirement has been updated to 1.11, but it's still listed as Java 1.8 in this documentation.

2022-08-16 18:23 UTC, aednichols approved these changes
Thanks for the PR!

I updated the link so that it tracks the latest version of the docs, instead of being fixed at Release 83. And, a blurb about how to actually install Java, because that consumes a surprising amount of time/help at workshops etc.

2022-08-16 18:23 UTC, aednichols commented on docs/tutorials/FiveMinuteIntro.md
> +	* If not, consider installing via conda or brew [as explained here](https://github.com/broadinstitute/cromwell/blob/83/docs/Releases.md).
```suggestion
	* If not, consider installing via conda or brew [as explained here](../Releases.md).
	* We recommend [SDKMAN](https://sdkman.io/install) to install the [Temurin](https://adoptium.net/temurin/releases/?version=11) build of Java
	  * `sdk install java 11.0.z-tem` where `z` is on the link above
```

2022-08-16 19:21 UTC, sjfleming commented
Yes, that seems like a good thing to add!

2022-08-16 20:06 UTC, sjfleming commented on docs/tutorials/FiveMinuteIntro.md
> +	* You can see what you have by running `$ java -version` on a terminal. You're looking for a version that's at least `1.11` or higher.
Actually I'm not at all sure (I'm not a java person), so I'll go with your suggestion!

2023-02-06 18:25 UTC, sjfleming commented
What are we thinking about these changes?  Look okay?

2023-02-07 21:54 UTC, aednichols commented
Looks like this was partially addressed in another merge and needs merge conflict updates: https://github.com/broadinstitute/cromwell/pull/6994

2023-02-21 15:24 UTC, sjfleming commented
I rebased.  Not sure if there's really enough left here to be worth it after 6994, but you can be the judge :)

2023-02-21 20:49 UTC, aednichols requested changes

2023-02-21 20:49 UTC, aednichols commented on docs/tutorials/FiveMinuteIntro.md
> +    * You can see what you have by running `$ java -version` on a terminal. You're looking for a version that's at least `1.11` or higher.
Don't think this is true, newer major releases of Java are not well-supported yet. Also, `1.11` should just be `11` as of... [2004 it looks like](https://en.wikipedia.org/wiki/Java_version_history#Release_table).

2023-02-21 21:49 UTC, aednichols approved these changes

2023-02-21 22:38 UTC, merged