WX-1010 Update Github Actions set output syntax
broadinstitute/cromwell pull request #7111
Opened 2023-04-04 14:30 UTC by aednichols

Per [Slack request](https://broadinstitute.slack.com/archives/C1EH66VCM/p1680287147009409) that came in during my user liaison shift. Old syntax to be deprecated in June 2023.

2023-04-04 14:54 UTC, jgainerdewar approved these changes

2023-04-04 15:41 UTC, knapii-developments requested changes

2023-04-04 15:41 UTC, knapii-developments commented on .github/workflows/trivy.yml
> +          echo "{image}=${image}" >> $GITHUB_OUTPUT
Same thing here: ```image=${image}" >> $GITHUB_OUTPUT```

2023-04-04 17:18 UTC, aednichols commented on .github/workflows/make_publish_prs.yml
> +          echo "{NEW_BRANCH_NAME}=${NEW_BRANCH_NAME}" >> $GITHUB_OUTPUT
I thought I copy-pasted exactly what you put in Slack... Is it really an unmatched quote `=${NEW_BRANCH_NAME}"`?

2023-04-05 13:34 UTC, THWiseman approved these changes

2023-04-05 20:19 UTC, knapii-developments approved these changes

2023-04-06 21:35 UTC, merged