Remove genomics/lifesciences usage from GCP Batch
broadinstitute/cromwell pull request #7411
Opened 2024-04-23 13:58 UTC by AlexITC

The Batch backend configuration depends on entries prefixed by "genomics" which is the wrong term, this entry has been renamed to "batch-api".

Also, the usages for these configs were renamed to "batch".

At last, there was an usage involving lifesciences which has been removed too.

NOTE: This is a breaking change, existing projecs using batch backend will need to update their configuration.

2024-04-24 19:28 UTC, AlexITC commented on supportedBackends/google/batch/src/main/scala/cromwell/backend/google/batch/actors/GcpBatchInitializationActor.scala
>                          CloudLifeSciencesScopes.CLOUD_PLATFORM,
I have tried removing this (`CloudLifeSciencesScopes.CLOUD_PLATFORM `) and `GenomicsScopes.GENOMICS` but centaur tests failed.

Does anyone know whether we should use a different scope? I'd expect that we shouldn't need anything lifesciences/genomics related (see https://github.com/broadinstitute/cromwell/actions/runs/8815748415/job/24198334692).

2024-05-14 14:50 UTC, aednichols requested changes
This could use a `CHANGELOG.md` entry to inform users about the config change. Maybe also explain that Batch support is in Alpha, hence there might be breaking changes.

2024-05-14 14:50 UTC, aednichols commented on supportedBackends/google/batch/src/test/scala/cromwell/backend/google/batch/actors/GcpBatchInitializationActorSpec.scala
> +      |  batch {
I'd personally prefer we use `batch` everywhere for consistency.

Seems easier to get right, especially when transitioning from a product we just called `genomics`.

2024-05-14 17:17 UTC, AlexITC commented
@aednichols the comments are resolved and tests are passing, thanks.

2024-05-14 17:59 UTC, aednichols approved these changes

2024-05-15 13:40 UTC, rsaperst approved these changes

2024-05-15 14:48 UTC, merged